# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to local Tomcat Server

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Step-1 Checkout the code
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn clean install
      
    - name: Deploy to tomcat
      run: mvn tomcat7:deploy
